### ISSUE TITLE
CIMultiDict.pop is case sensitive.

### ISSUE THREAD

**Issue by Lukasa** [aio-libs/multidict#1]
### Repro Steps

```python
>>> from multidict import CIMultiDict
>>> d = CIMultiDict(key='value')
>>> d['key']
'value'
>>> d.pop('key')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "multidict/_multidict.pyx", line 385, in multidict._multidict.MultiDict.pop (multidict/_multidict.c:7811)
KeyError: 'key'
```

### Expected Behaviour

Calling `pop` should return `'value'` and remove the item from the dict.

### Actual Behaviour

`KeyError`

### Environment

**Python**: Python 3.5.1 (default, Dec 14 2015, 09:21:15)  [GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin

**System**: Mac OS X El Capitan 10.11.5

**multidict version**: 1.0.3, installed from PyPI

**Comment by asvetlov** [comment]
Fixed by 011030a
