### ISSUE TITLE
Implementation thoughts

### ISSUE THREAD

**Issue by mahmoud** [aio-libs/multidict#10]
Hi there! Great project! I was reviewing the implementation (love the cython bindings), but it occurred to me: have you considered using a linked-list + dict approach for the internals of the MultiDict? I may be wrong, but as it stands now, it seems like the access time may be O(n). It's good because it seems to preserve order, which I appreciate (some servers are header-order sensitive and query param order-sensitive).

I understand O(n) is probably ok most of the time for some protocols (HTTP probably has <10 headers on most requests), but I figured I'd ask anyway. Keep up the great work!

**Comment by asvetlov** [comment]
I've tries to use an approach like you are suggesting.
Seems I've got no speedup but implementation was much more complex.

If anybody will publish a patch with benchmark measurements I'd love to review it but right now I think that performance is just *good enough* to stop investing my own time into it.
