### ISSUE TITLE
public class _Base

### ISSUE THREAD

**Issue by aamalev** [aio-libs/multidict#102]
To effective detect a group of classes

    if isinstance(a, BaseMultidict):
        # dosomething1
    elif isinstances (a, Mapping):
        # dosomething2

The simplest implementation is less effective

    BaseMultidict = (CIMultiDict, MultiDict, MultiDictProxy)

**Comment by asvetlov** [comment]
No. It is implementation detail and subject of future changes.
Next versions may have no such base class at all.

BTW what use cases for checking this type? Theoretically what you need is iteration over `a.items()` regardless concrete `Mapping` implementation.

**Comment by aamalev** [comment]
The main project classes have a common interface described by common methods. Based on the principles of parametric polymorphism, it makes sense to single out a formally generalized interface. For python parametric polymorphism goes along with annotations and types such as Mapping, but Mapping exclude getall

In this case https://github.com/aamalev/aiohttp_apiset/blob/master/aiohttp_apiset/swagger/route.py#L132 could get away from duck typing

**Comment by asvetlov** [comment]
In this case you need multidict ABCs for extending standard Mapping and MutableMapping.
I'm open for PR like this (documentation should be updated as well).
Personally I don't have very strong motivation for fixing it myself right now.
