### ISSUE TITLE
Consider moving package to `src` subfolder

### ISSUE THREAD

**Issue by webknjaz** [aio-libs/multidict#127]
As per https://hynek.me/articles/testing-packaging/ when testing `--editable` (`develop`) install you are not testing the package installed same way as it will be installed in by users.

@asvetlov what do you think about such approach? Sounds reasonable to me.

**Comment by asvetlov** [comment]
I doubt if it's necessary

**Comment by webknjaz** [comment]
@asvetlov do you consider this a bad practice? what about other repos?

**Comment by asvetlov** [comment]
I think effect is negligible.
Pushing into `src` is not bad but doesn't make benefits.
We do test non-editable installation on making manylinux wheels, could modify travis to do the same for regular PRs too.
I really see no point in adding extra folder and increasing nesting level.

**Comment by webknjaz** [comment]
> We do test non-editable installation on making manylinux wheels

We do installation, but tests still import modules from the local directory, it's right in CWD, next to tests, which higher priority than site-packages.
Does this sound correct to you?

**Comment by asvetlov** [comment]
You are right.
```
In [1]: import sys

In [2]: sys.path
Out[2]: 
['',
 '/home/andrew/.virtualenvs/multidict/bin',
 '/home/andrew/.virtualenvs/multidict/lib/python36.zip',
 '/home/andrew/.virtualenvs/multidict/lib/python3.6',
 '/home/andrew/.virtualenvs/multidict/lib/python3.6/lib-dynload',
 '/usr/lib/python3.6',
 '/home/andrew/.virtualenvs/multidict/lib/python3.6/site-packages',
 '/home/andrew/projects/multidict',
 '/home/andrew/.virtualenvs/multidict/lib/python3.6/site-packages/IPython/extensions',
 '/home/andrew/.ipython']
```

Maybe ```
cd tests
pytest .
```
could solve the problem without need for directory structure change?
Otherwise we need to add `src` everywhere including `aiohttp`.

**Comment by webknjaz** [comment]
> cd tests

This means explaining how to run tests to users everywhere in docs and maybe wrapping testing with `tox` or similar to achieve same way of running tests across. Sounds to me like multiple points of misleading docs

> Otherwise we need to add `src` everywhere including `aiohttp`

Sure, this looks easier to me.

P.S. I'm also thinking about copying just tests somewhere and running pytest against installed wheel and that test folder.

**Comment by asvetlov** [comment]
If we will do proper test run on travis -- it would be enough.
I expect very rare rate of such errors.
Users could still run tests in editable mode.
Changing directory structure in aiohttp is the thing I want to avoid but we could change travis instructions without any limitations.

**Comment by webknjaz** [comment]
I'm going to experiment with that and also play with in-container testing, then.

**Comment by gagoman** [comment]
As `tox` is not used I think it is not an issue for this project.
It is an issue for projects that have `tox` and C extensions though.

**Comment by webknjaz** [comment]
I think it's not tox-related

**Comment by gagoman** [comment]
It is `tox` related, at least what is described in initial link.

Tox first packages your code but then uses develop version and not what you've installed.
I've noticed that when I was writing a package with Cython extension and testing it with different versions. It was always complaining about missing `so`.

Without tox you actually want pytest to test your develop version.

**Comment by webknjaz** [comment]
not really, the point there is that you want to test installed package and make tests import that rather than package in CWD

**Comment by webknjaz** [comment]
I think Alex is right, closing this issue then.

**Comment by webknjaz** [comment]
Apparently, pytest adds CWD to `PYTHONPATH` when invoked via `python -m pytest`.
