### ISSUE TITLE
Upload linux wheels doesn't work

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/multidict#135]
See
https://pypi.python.org/pypi?:action=display&name=multidict&version=3.3.0a1#downloads

Maybe handling travis deploy instruction has changed, don't know.
I'm inclined to use `twine` explicitly for uploading both tarball and manylinux wheels.

Moreover `./tools/run_docker.sh "multidict"` generates extra `_istr.xx.so` for `python 3.6` even it is executed for building `3.4`  wheel.

I'll try to investigate what's going on.
@webknjaz if you have a time to take a look --- it would be awesome.
You are travis jedi, I suspect the deploy is broken after your changes in our build process.

**Comment by webknjaz** [comment]
@asvetlov wow! ..at least I see 3.1.4a3 manylinux1 wheels in place

But why did you skip v3.2 exactly?

**Comment by webknjaz** [comment]
This _might_ be related to roll-out of their second iteration of build stages. There's no deploy step in build log present.

**Comment by webknjaz** [comment]
Ref: https://github.com/travis-ci/beta-features/issues/28#issuecomment-329598426

**Comment by webknjaz** [comment]
Let's wait for their answer till tomorrow.

**Comment by webknjaz** [comment]
Plz also note that they've got some issues with their infra currently: https://www.traviscistatus.com/incidents/n90wqynjt6k0

**Comment by asvetlov** [comment]
> But why did you skip v3.2 exactly?

Ooops. My mistake

**Comment by webknjaz** [comment]
https://github.com/travis-ci/travis-ci/issues/8337#issuecomment-326838809

**Comment by webknjaz** [comment]
I think, I've fixed it. Ping me in case of any questions ;)
