### ISSUE TITLE
clarification on versioning

### ISSUE THREAD

**Issue by anthraxx** [aio-libs/multidict#136]
Hi, I'm a distro packager and curious about the versioning with 'a'.
Are v3.1.4a0  … v3.3.0a0 meant to be alpha releases that should not be distributed?
Or are those now "regular" version schemes and distros should pick up those versions?

thanks for clarifying and sorry for the noise

**Comment by asvetlov** [comment]
Yes, 'a' is a standard shortcut for `alpha`, 'b' for `beta`.
`pip` doesn't install these packages until `pip install --pre <package>` option is specified.
I use alpha/beta releases sometimes for testing purposes.
E.g. now I did it to test our autodeply procedure (which was proven to be broken).

**Comment by anthraxx** [comment]
Thanks for explaining and sorry for the noise
Cheers

**Comment by asvetlov** [comment]
no problems
