### ISSUE TITLE
ItemsView behavior

### ISSUE THREAD

**Issue by gagoman** [aio-libs/multidict#159]
Good day.

I'm currently trying to rewrite multidict on top of OrderedDict/dict (4fun) and faced a behavior that is not clear for me.

So `_ItemsView` returns a items in order they appear and that is correct. Nonetheless we are not able to retrieve values by keys in this example:

```
d2 = MultiDict([('1', 'foo'), ('2', 'bar'), ('1', 'baz')])
for k in d2:
    print('%s => %s' % (k, d2[k]))
    
1 => foo
2 => bar
1 => foo
```

I know that it is a right behavior for `MultiDict` but is it a most expected one?

**Comment by webknjaz** [comment]
There's [`MultiDict.getall(key, default=_marker)`](https://github.com/aio-libs/multidict/blob/master/multidict/_multidict.pyx#L98-L118) for pulling all key's values.

Getting a single value by its key should remain the same regardless of how many times you called it.

**Comment by asvetlov** [comment]
Also you could iterate over key/value pairs:
```
In [3]: d = MultiDict([('1', 'foo'), ('2', 'bar'), ('1', 'baz')])

In [4]: for k, v in d.items():
   ...:     print(k, v)
   ...:     
1 foo
2 bar
1 baz
```

`__getitem__` is and alias for `getone()` which returns a **first** found value.

**Comment by asvetlov** [comment]
Internally multidict is a sequence of key/value pairs.
This is very important: HTTP headers are ordered and sometimes, in very rare cases, it is crucial.
The order should be not changed after serializing headers back.

**Comment by gagoman** [comment]
I know about `items` and `getall`. Just wanted to clarify that you are aware of this behavior. Thank you a lot.

Offtopic question not to raise another issue:
Is it crucial to have an order not changed only for a specific header or for a sequence of headers also?

I just want to understand if it makes sense trying to implement it on top of regular dicts. With OrderedDict prior python 3.6 and regular dict on 3.6 we can achieve order for values for a specific header, but not for a headers themselves. I've seen https://github.com/aio-libs/multidict/issues/68#issuecomment-303915407

**Comment by asvetlov** [comment]
Yes, I understand.
It's a subtle matter but for example `Forwarded` and `X-Forwarded-*` headers might overlap.
I thought about keeping order for values inside a key only.
Moreover early multidict implementations was built in this way.
But later I've switched to linear key-value pairs sequence because people was confused at least.

**Comment by webknjaz** [comment]
@gagoman I consider the question answered. Feel free to reopen it if you have any further questions.
