### ISSUE TITLE
[notification] Sviatoslav Sydorenko has given admin rights

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/multidict#166]
@webknjaz has given admin rights for the project.
He worked hard on travis and deployment setup, new access privileges will help him to do his duty faster and better.
He is a committer already BTW

**Comment by webknjaz** [comment]
Thanks!

**Comment by jettify** [comment]
Wellcome!  We have bunch other project where we can improve travis :) just saying  :wink:

**Comment by webknjaz** [comment]
I know, me too :) It's just a staging playground before breaking stuff at scale)
