### ISSUE TITLE
Cython and Python versions of CIMultiDict treat key case differently

### ISSUE THREAD

**Issue by mikenerone** [aio-libs/multidict#202]
First noticed this in 3.3.2 (probably existed before that), still exists in 4.0.0:

As one would expect (IMO) the Cython version uses the title-ized key for matching and preserves the original key for output/serialization. The Python version throws away the original key completely and uses the title-ized key for both purposes, breaking output. Again, that's my opinion, but in any case, the behavior should be the same.

```python
In [1]: from multidict._multidict import CIMultiDict  # Cython

In [2]: md = CIMultiDict()
   ...: md['some_key'] = 1
   ...: list(md.items())
   ...:
Out[2]: [('some_key', 1)]  # outputs original key

In [3]: from multidict._multidict_py import CIMultiDict  # Python

In [4]: md = CIMultiDict()
   ...: md['some_key'] = 1
   ...: list(md.items())
   ...:
Out[4]: [('Some_Key', 1)]  # outputs title-ized key
```

**Comment by mikenerone** [comment]
Having thought about it, I'm more on the fence about _which_ behavior is more correct. The title-style output makes sense for HTTP headers. :/

**Comment by asvetlov** [comment]
In this case Cython version is correct, pure Python should be fixed

**Comment by mikenerone** [comment]
Cool, I'll be happy to make a PR if you like. I can be a contributor for just one line. :P

**Comment by asvetlov** [comment]
Please do.
Thank you for report

**Comment by webknjaz** [comment]
> I can be a contributor for just deleting one line.

One line and a test, please:)

**Comment by mikenerone** [comment]
I noticed the same effect in the Python implementation in several of the places where a `KeyError` is raised, where the error message includes the title-ized key instead of the key passed by the caller (again, unlike the Cython implementations, which handle this correctly). As it's basically the same logic error, would you like me to fix these, as well?

**Comment by asvetlov** [comment]
Yes, casing should be preserved as Cython version does.
