### ISSUE TITLE
Support PEP-561

### ISSUE THREAD

**Issue by bryanforbes** [aio-libs/multidict#219]
[PEP-561](https://www.python.org/dev/peps/pep-0561/) enables package maintainers to distribute their typing stub files and have mypy (as of version 0.590) use them from the installed package. Since multidict already includes stub files, the only thing that needs to be done is to distribute a file named `py.typed` in the package directory.

**Comment by webknjaz** [comment]
@bryanforbes thank you for the suggestion. While I don't have time to check how it works right now, I'm just gonna say that PR is welcome ;)

**Comment by webknjaz** [comment]
I have just noticed that @asvetlov has already solved this issue via 528f924.
