### ISSUE TITLE
TODO: Try enabling extensions under pypy3 v6.0 once it's available in Travis CI and/or pyenv

### ISSUE THREAD

**Issue by webknjaz** [aio-libs/multidict#223]
It looks like they've improved compatibility with CPython in v6.0

Ref: https://twitter.com/pypyproject/status/989392997300260865
Ref: travis-ci/travis-ci#9542

**Comment by asvetlov** [comment]
We have Pure Python version, why should we care about cpyext?

**Comment by webknjaz** [comment]
It's just personal curiosity, I want to see how it goes.

**Comment by asvetlov** [comment]
Ok, NP

**Comment by asvetlov** [comment]
Multidict on PyPy should work in pure Python mode, and it does already.
Closing the issue
