### ISSUE TITLE
setup.py test failed: unrecognized arguments: --cov=multidict

### ISSUE THREAD

**Issue by socketpair** [aio-libs/multidict#225]
```
DEBUG: + /usr/bin/python3.5 setup.py test
DEBUG: running pytest
DEBUG: running egg_info
DEBUG: writing multidict.egg-info/PKG-INFO
DEBUG: writing top-level names to multidict.egg-info/top_level.txt
DEBUG: writing dependency_links to multidict.egg-info/dependency_links.txt
DEBUG: reading manifest file 'multidict.egg-info/SOURCES.txt'
DEBUG: reading manifest template 'MANIFEST.in'
DEBUG: warning: no files found matching 'CHANGES.rst'
DEBUG: warning: no previously-included files matching '*.pyc' found anywhere in distribution
DEBUG: warning: no previously-included files found matching 'multidict/_multidict.html'
DEBUG: warning: no previously-included files found matching 'multidict/_multidict.pyd'
DEBUG: warning: no previously-included files found matching 'multidict/_multidict.*.pyd'
DEBUG: no previously-included directories found matching 'docs/_build'
DEBUG: writing manifest file 'multidict.egg-info/SOURCES.txt'
DEBUG: running build_ext
DEBUG: usage: setup.py [options] [file_or_dir] [file_or_dir] [...]
DEBUG: setup.py: error: unrecognized arguments: --cov=multidict
DEBUG:   inifile: /builddir/build/BUILD/multidict-4.2.0/pytest.ini
DEBUG:   rootdir: /builddir/build/BUILD/multidict-4.2.0
```

**Comment by asvetlov** [comment]
I don't use `python setup.py test` personally.
Looks like we need to install `pytest-cov` here: https://github.com/aio-libs/multidict/blob/master/setup.py#L80

Would you make a PR?

**Comment by socketpair** [comment]
1. Anyway, it dowsn't work, it also requires `perf` python package...
2. Our build system calls `python setup.py test` for every package we build.

Yes, I will make PR later.

**Comment by webknjaz** [comment]
@socketpair this way of running tests is considered harmful, so we don't really use it ourselves. But yes, feel free to try playing with it via:
```python
from pip.req import parse_requirements

# parse_requirements() returns generator of pip.req.InstallRequirement objects
test_reqs = parse_requirements('requirements/dev.txt')

# reqs is a list of requirement
# e.g. ['django==1.5.1', 'mezzanine==1.4.6']
reqs = [str(ir.req) for ir in test_reqs]
```

**Comment by asvetlov** [comment]
@webknjaz IIRC `pip` has dropped all its public API (moved into `pip._internal` actually).
The code should not rely on any pip function.

**Comment by gyermolenko** [comment]
@socketpair FYI I didn't reproduce your situation with `python setup.py test`. 
My setup was: `multidict` from master (4.4.2+) and 
- python 3.5.5
- python 3.7.0
Had no errors and 680 passed tests.

**Comment by webknjaz** [comment]
@gyermolenko ideally I'd like to fully remove `test` command, it's not a common way of running test and is officially discouraged.

**Comment by gyermolenko** [comment]
> @gyermolenko ideally I'd like to fully remove `test` command, it's not a common way of running test and is officially discouraged.

I wasn't promoting it)) just wanted to say that the defect was already fixed and probably should have been closed a long time ago..

**Comment by webknjaz** [comment]
I guess
