### ISSUE TITLE
TODO: Add multiple issue templates to evaluate how it works

### ISSUE THREAD

**Issue by webknjaz** [aio-libs/multidict#226]
GitHub has publicly released feature of having several different templates for different issue types a few days ago. It looks pretty neat and I'm looking forward to integrating them into other projects.

Ref: maintainers/early-access-feedback#139

**Comment by kxepal** [comment]
> Ref: maintainers/early-access-feedback#139

Page not found :crying_cat_face:

**Comment by webknjaz** [comment]
It's a closed community, but the feature is public. @asvetlov will be able to see it.

**Comment by asvetlov** [comment]
I do.
If you want to enable and setup it -- welcome.
Otherwise, the issue goes to backlog for very long time :)

**Comment by webknjaz** [comment]
I've enabled it, but did not add a fallback template yet.

**Comment by webknjaz** [comment]
(https://github.com/aio-libs/multidict/issues/new/choose)

**Comment by webknjaz** [comment]
It can be even nicer!
https://twitter.com/left_pad/status/992163857404645376?s=19
