### ISSUE TITLE
Broken Travis CI: last build registered was 20 days ago

### ISSUE THREAD

**Issue by webknjaz** [aio-libs/multidict#229]
@asvetlov it looks like github's webhook requests have stopped reaching Travis CI. I'm gonna write them and ask to move this project to the new platform.

**Comment by asvetlov** [comment]
Sounds good.
I'll publish a new release manually now.

**Comment by webknjaz** [comment]
Action items:
- [ ] reach out to Travis CI
- [ ] research possibilities to monitor similar outages

**Comment by asvetlov** [comment]
From my side I see nothing wrong with Travis config.

**Comment by webknjaz** [comment]
It's not related to the config. Travis CI requests page does not show any queries from GitHub. So it's either stuck somewhere in the CI's webhook processing or integration has been broken for this repo within github.
Taking into account that old GitHub Services integration is being deprecated I don't see any reason to stick with it, thus it's better to move to a new place and see how it goes.

**Comment by asvetlov** [comment]
Ok

**Comment by webknjaz** [comment]
Closing in favor of aio-libs/night-watch#2
