### ISSUE TITLE
Github templates are not relevant to the project

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/multidict#230]
See the template below.
Multidict has no button to click and has no OS/Browser specific

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by webknjaz** [comment]
I'll ask @serhii73 to work on this, he needs practice in his first steps towards starting doing open source contributions. Please avoid solving it yourself.

**Comment by asvetlov** [comment]
Cool!
