### ISSUE TITLE
Create a separate GitHub App for doing deployments to PYPI [actually it's for all aio-libs]

### ISSUE THREAD

**Issue by webknjaz** [aio-libs/multidict#235]
I want to listen to Deployment events from this service, while Deployments themselves should be fired by CI services (Travis, AppVeyor etc.).

The idea is to use this service as a synchronization primitive and publish all wheels simultaneously, so that there won't be any time lag between different architecture-specific wheels appearing on PYPI.

I'm currently experimenting with this.

Ref: https://github.com/Scifabric/deployments
Ref: pypa/warehouse#4056
Ref: aio-libs/multidict#182
Ref: aio-libs/aiohttp#2347
Ref: https://github.com/attobot/attobot
Ref: https://github.com/pypa/warehouse/issues/3963

**Comment by asvetlov** [comment]
Now Azure is the single tool for all the project deployments.
If it fails nothing is uploaded on PyPI.

The current situation works perfectly fine for the project needs.
