### ISSUE TITLE
pypi wheel for python3.7

### ISSUE THREAD

**Issue by wwqgtxx** [aio-libs/multidict#267]
the Python3.7 was released, would the py37 wheels add to pypi.org?

**Comment by asvetlov** [comment]
Thanks for raising the issue.
It's on my radar.
Perhaps we will publish all multidict, yarl and aiohttp binary wheels at the same time.
Need to check our auto-deployment process for Python 3.7 and make sure that everything works.

**Comment by webknjaz** [comment]
Well need to adjust one variable in manylinux1 script and in osx, but I didn't check what's the state of Python in Appveyor.

**Comment by webknjaz** [comment]
Done: https://pypi.org/project/multidict/4.4.0/#files
