### ISSUE TITLE
CIMultiDict add does not work as expected

### ISSUE THREAD

**Issue by pgjones** [aio-libs/multidict#273]
**Describe the bug**
```
>>> a = CIMultiDict()
>>> a.setdefault('lower', 2)
2
>>> a.add('Lower', 3)
>>> a
<CIMultiDict('lower': 2, 'Lower': 3)>
>>> a['Lower']
2
>>> a.getall('lower')
[2, 3]
>>> a.keys()
_KeysView('lower', 'Lower')
```

I think it should be either 'Lower' or 'lower' rather than having two keys (given it is a *CI*MultiDict).

**To Reproduce**   
As above.

**Your version of the Python**
3.7

**Your version of the multidict distribution**
4.3.1

**Comment by asvetlov** [comment]
It does.
You have two key/value pairs in the dict.
`repr()` preserves the key case. `CIMultiDict` is case insensitive on getting/setting, not printing.

5 cents for meditation:
```
In [1]: from multidict import CIMultiDict

In [2]: m = CIMultiDict

In [3]: m = CIMultiDict()

In [4]: m.setdefault('a', 1)
Out[4]: 1

In [5]: m.add('a', 2)

In [6]: m.keys()
Out[6]: _KeysView('a', 'a')
```
Two identical keys again :)

**Comment by pgjones** [comment]
Hmm, maybe the confusion is on my part but I would not expect this:
```
>>> a = CIMultiDict()
>>> a.add('a', 1)
>>> a.add('A', 2)
>>> for key, value in a.items():
...     print(key, value)
... 
a 1
A 2
>>> a['a']
1
>>> a['A']
1
>>> a.getall('a')
[1, 2]
```
Wouldn't it make sense for there just to be one 'a' key given the Case Insensitive nature?

**Comment by pgjones** [comment]
I think I see. (It was the for loop part that was throwing me)
