### ISSUE TITLE
How to get original casing for key?

### ISSUE THREAD

**Issue by bmintz** [aio-libs/multidict#298]
I'm writing a Discord bot that notifies users when certain words are said in chat.
The highlight words are case insensitive.
Currently, I'm using a `CIMultiDict` to map highlight word -> user who subscribes to that highlight word.
Like this:
`<CIMultiDict('abc': 123, 'ABC': 456, 'abc': 789)>`
This means that when 'abc' is said in chat, users 123, 456, and 789 will be notified.

I want to notify users 123 and 789 that they were highlighted because they subscribed to "abc",
but I want to notify user 789 that they were highlighted because they subscribed to "ABC".

How can I do this?

**Comment by bmintz** [comment]
My code is roughly this:
```py
        highlight_users, regex = get_channel_highlights(message.channel)
        seen_users = set()
        for match in re.finditer(regex, message.content):
            highlight = match[0]  # this uses the case of the original message, not the case that the user subscribed to (in the example above, it's "abc", not "ABC")
            for user_id in highlight_users.getall(highlight):  # this is the problematic line because case is swallowed
                if user_id not in seen_users and user_id != message.author.id:
                    yield user_id, highlight
                    seen_users.add(user_id)
```

Ideally I would have a way to get a list/iterator of (key, value) pairs for a particular key.
The keys would be the original casing of the highlight words that the user subscribed to.
Value would be who to notify.

**Comment by asvetlov** [comment]
Sorry.
aiohttp has no such functionality and I doubt if we want to add it
