### ISSUE TITLE
TODO: add verification of noexecstack in *.so files when making wheels

### ISSUE THREAD

**Issue by webknjaz** [aio-libs/multidict#317]
Ref: https://github.com/pyca/cryptography/pull/4130

**Comment by asvetlov** [comment]
Why is this required?
The modern compiler/linker does the right thing out of the box, isn't it?

**Comment by webknjaz** [comment]
Just for double-checking the resulting artifacts.

**Comment by asvetlov** [comment]
It makes sense for an encryption library to prevent vulnerabilities, HEARTBLEED is a nice example.
For the multidict, I doubt if we need additional steps.
