### ISSUE TITLE
Announcement: give commit rights to Igor Emelianov

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/multidict#319]
At first, I want to very big thank to @iemelyanov 
Hi contributed to the project a lot.
Now he is the main driver.
The commit right is a kind of grateful acknowledgment for Igor's hard work.

I'm keeping the project leader role, the final responsibility for project bugs etc. is still my duty.
But any help is welcome, sure.
@webknjaz thank you very much for maintaining our automation processes in a good shape as well.

P.S.
Committer role assumes more responsibility with almost no real benefits.
All code changes should go through Pull Requests, review process etc.
The only real change that a committer can proud of a new GitHub badge in his profile, as I do for CPython and aio-libs & aiohttp ;)

**Comment by webknjaz** [comment]
+1

**Comment by kxepal** [comment]
+1 Congratulations!

**Comment by webknjaz** [comment]
@iemelyanov you need to accept that org invitation for this to work :)

**Comment by iemelyanov** [comment]
Dear Andrew, thank you for appreciation! I am happy to have joined the project. Your kind guidance is priceless. I tried my best! :)
