### ISSUE TITLE
BadContentDispositionHeader Failure

### ISSUE THREAD

**Issue by Severogor** [aio-libs/multidict#337]
Hi, Andrew!

Firstly, I'd like to thank you for the aiohttp library!

I'm encountering the following error while handling file uploads: in case when the client uploads multipart data with filename field consisting of:
";" or containing it more than once,
"/"
and possibly some other symbols
 -- the whole upload fails.

```
/var/srv/lib/python3.7/site-packages/aiohttp/multipart.py:157:
BadContentDispositionHeader: form-data; name="0000"; filename="&#1088;&#1055;"
 warnings.warn(BadContentDispositionHeader(header))
Error handling request
Traceback (most recent call last):
  File "/var/srv/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/var/srv/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/var/srv/api/handlers/authorization.py", line 33, in wrapper
    return await f(request)
  File "/var/srv/api/handlers/upload.py", line 163, in upload
    post = await request.post()
  File "/var/srv/lib/python3.7/site-packages/aiohttp/web_request.py", line 642, in post
    out.add(field.name, value)
  File "multidict/_multidict.pyx", line 264, in
multidict._multidict.MultiDict.add
  File "multidict/_multidict.pyx", line 257, in
multidict._multidict.MultiDict._add
TypeError: MultiDict keys should be either str or subclasses of str
```
Shouldn't the system handle such cases somehow as far as the filename field is quoted and (if I understand it correctly) therefore may consist of mostly everything?

The version of MultiDict is 4.5.2.

Thanks!
S.

**Comment by webknjaz** [comment]
Hi @Severogor,

To me, it looks like the failure is legit. But of course, there's no way to say whose error this is without a proper reproducer posted here.

It's pretty obvious and expected that having a semicolon there is bad for parsing. Let me check the RFC just to be sure.

**Comment by webknjaz** [comment]
https://tools.ietf.org/html/rfc7578#section-4.3 -> https://tools.ietf.org/html/rfc2183#section-2.3 -> https://tools.ietf.org/html/rfc1521

     value := token / quoted-string

     token  :=  1*<any (ASCII) CHAR except SPACE, CTLs,
                   or tspecials>

     tspecials :=  "(" / ")" / "<" / ">" / "@"
                /  "," / ";" / ":" / "\" / <">
                /  "/" / "[" / "]" / "?" / "="
               ; Must be in quoted-string,
               ; to use within parameter values

This suggests that using `;` there is forbidden.

**Comment by asvetlov** [comment]
I guess you use non-string (an integer most likely) as a field name.
multidict doesn't handle arbitrary key types.
