### ISSUE TITLE
can't pickle CIMultiDictProxy objects

### ISSUE THREAD

**Issue by samuelcolvin** [aio-libs/multidict#340]
Works for `CIMultiDict` but not `CIMultiDictProxy`.

Surely not difficult

```
In [1]: from multidict import CIMultiDict, CIMultiDictProxy                                                                                                                       

In [2]: d = CIMultiDict()                                                                                                                                                         

In [3]: d['Foo'] = 1                                                                                                                                                              

In [4]: import pickle                                                                                                                                                             

In [5]: pickle.dumps(d)                                                                                                                                                           
Out[6]: b'\x80\x03cmultidict._multidict\nCIMultiDict\nq\x00]q\x01X\x03\x00\x00\x00Fooq\x02K\x01\x86q\x03a\x85q\x04Rq\x05.'

In [6]: d_proxy = CIMultiDictProxy(d)                                                                                                                                             

In [7]: pickle.dumps(d_proxy)                                                                                                                                                     
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-8-218ff57aadfa> in <module>
----> 1 pickle.dumps(d_proxy)

~/code/em2/env/lib/python3.7/site-packages/multidict/_multidict.pyx in multidict._multidict.MultiDictProxy.__reduce__()

TypeError: can't pickle CIMultiDictProxy objects
```

**Comment by samuelcolvin** [comment]
as per #77 it was decided that `CIMultiDictProxy` should explicitly not support pickling. I think this is unfortunate.

For example the exception raised by `raise_for_status=True` in aiohttp is not picklable because of this. @asvetlov would you reconsider? Happy to work on a PR if you do.

**Comment by asvetlov** [comment]
Let's discuss it.
The main reason for forbidding is that the multidict proxy follows `types.MappingProxyType` design.

I'm curious why do you want to pickle aiohttp exceptions? Maybe for this particular case better to add pickling to exception class explicitly?

**Comment by samuelcolvin** [comment]
[arq](https://github.com/samuelcolvin/arq) pickle's exceptions from jobs so they can be raised when getting the result of a job (roughly equivalent of getting the result of an asyncio task). 

For now I've fixed it to catch errors when pickling, but I imagine there are other cases where pickling `CIMultiDictProxy` might be useful.

**Comment by asvetlov** [comment]
`arq` needs were my first thought :)

I see the reason for proxy object pickling forbidding.
Let's assume we have the following:
```
md = MultiDict(a='1', b='2')
mp = MultiDictProxy(md)
```
change in multidict is still reflected in proxy:
```
In [9]: md['c'] = '3'                                                                                                                             

In [10]: mp                                                                                                                                       
Out[10]: <MultiDictProxy('a': '1', 'b': '2', 'c': '3')>
```
But pucking `mp` and unpickling it back creates a new `MultiDict` object source for the proxy, I don't see a way how to restore the link to `md` back.

After the pickle-unpickle cycle, the proxy is not coupled with the source multidict anymore, changing `md` doesn't magically change a new unpickled `mp` instance content.

This is the design decision: `MultiDictProxy` is really a proxy, not a read-only copy.
Proxy behavior can be useful sometimes, for collecting a mutable HTTP headers multidict but returning immutable proxy is pretty cheap.
Unfortunately, it the direct consequence of this design is forbidding the pickling of proxy objects.

Did I miss something?

**Comment by samuelcolvin** [comment]
no, that makes sense. 

I was assuming you'd have to implicitly copy the underlying `MultiDict` so pickling works.

Since the logging that requires access to the multidict will occur on the worker since, I can easily work around this in arq by just returning `RuntimeError('unable to pickle error')`.

As always with python, the problem is the unexpected exception, maybe one day I'll move everything to rust, but for now life is too short.

Thanks for the response.

**Comment by User087** [comment]
> `arq` needs were my first thought :)
> 
> I see the reason for proxy object pickling forbidding. Let's assume we have the following:
> 
> ```
> md = MultiDict(a='1', b='2')
> mp = MultiDictProxy(md)
> ```
> 
> change in multidict is still reflected in proxy:
> 
> ```
> In [9]: md['c'] = '3'                                                                                                                             
> 
> In [10]: mp                                                                                                                                       
> Out[10]: <MultiDictProxy('a': '1', 'b': '2', 'c': '3')>
> ```
> 
> But pucking `mp` and unpickling it back creates a new `MultiDict` object source for the proxy, I don't see a way how to restore the link to `md` back.
> 
> After the pickle-unpickle cycle, the proxy is not coupled with the source multidict anymore, changing `md` doesn't magically change a new unpickled `mp` instance content.
> 
> This is the design decision: `MultiDictProxy` is really a proxy, not a read-only copy. Proxy behavior can be useful sometimes, for collecting a mutable HTTP headers multidict but returning immutable proxy is pretty cheap. Unfortunately, the direct consequence of this design is forbidding the pickling of proxy objects.
> 
> Did I miss something?

Is it possible to access the underlying MultiDict of a `response` and pickle that? If so, how? I didn't find any explanation in the [docs](https://docs.aiohttp.org/en/stable/client_reference.html#aiohttp.ClientResponse).
