### ISSUE TITLE
[TODO] Add Pickle v5 to the test suite

### ISSUE THREAD

**Issue by webknjaz** [aio-libs/multidict#362]
I guess it's the same as #296.

**Comment by gyermolenko** [comment]
Reference of the related change: [whatsnew in 3.8](https://docs.python.org/3.8/whatsnew/3.8.html#pickle-protocol-5-with-out-of-band-data-buffers)
Not present in the list of available protocols yet [2019-08-29]: [pickle-protocols](https://docs.python.org/3.8/library/pickle.html#pickle-protocols)

Although `HIGHEST_PROTOCOL` version is now indeed 5 [src](https://github.com/python/cpython/blob/91f4380cedbae32b49adbea2518014a5624c6523/Lib/pickle.py#L60) - maybe it is better to wait for 3.8 release?

**Comment by gyermolenko** [comment]
Hm. I wanted to try it out but can't install from master
```pycon
$ pip list | grep Cython
Cython                        0.29.13

$ pip install -e .
Obtaining file:///home/gy/code/forks/multidict
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /home/gy/.pyenv/versions/3.7.4/envs/multidict-3.7.4/bin/python3.7 /home/gy/.pyenv/versions/3.7.4/envs/multidict-3.7.4/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpb2dbslfs
       cwd: /home/gy/code/forks/multidict
  Complete output (3 lines):
  Install cython when building from git clone
  Hint:
    pip install cython
  ----------------------------------------
ERROR: Command errored out with exit status 1: /home/gy/.pyenv/versions/3.7.4/envs/multidict-3.7.4/bin/python3.7 /home/gy/.pyenv/versions/3.7.4/envs/multidict-3.7.4/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpb2dbslfs Check the logs for full command output.
```

Same error for 3.7.4 and 3.8-dev (b3+). 
For Python 3.6.6 installs succesfully. Wonder if it is because of Cython.

**Comment by webknjaz** [comment]
> Install cython when building from git clone

**Comment by webknjaz** [comment]
It's because you don't have Cython pre-installed in that env

**Comment by webknjaz** [comment]
> maybe it is better to wait for 3.8 release?

It's failing in CI on `nightly`. So we need to update it already.

**Comment by gyermolenko** [comment]
> It's because you don't have Cython pre-installed in that env

I guess I have it
```pycon
$ pip list | grep Cython
Cython                        0.29.13
```

**Comment by webknjaz** [comment]
Try `pip install --no-build-isolation .`

**Comment by gyermolenko** [comment]
> Try pip install --no-build-isolation .

It worked, thanks. 
btw `--no-use-pep517` also works
