### ISSUE TITLE
[TODO] Figure out how to integrate `tox --devenv` into `Makefile`

### ISSUE THREAD

**Issue by webknjaz** [aio-libs/multidict#364]
https://github.com/tox-dev/tox/pull/1326

**Comment by hmajid2301** [comment]
I can take a look at this.

**Comment by webknjaz** [comment]
Sure, go ahead!

**Comment by webknjaz** [comment]
#370 doesn't do what the issue asks. This is still unsolved.

**Comment by hmajid2301** [comment]
sorry i misunderstood what do you need it to do ?

**Comment by webknjaz** [comment]
The issue title says that you need to integrate `--devenv` CLI option to allow creating dev virtualenvs based on existing toxenv definitions. The PR where this feature was added is linked, so you can track down how it works. We don't need another toxenv in `tox.ini`.

**Comment by hmajid2301** [comment]
so something like `make dev virtualenv=.venv PY=3.6`.

**Comment by webknjaz** [comment]
`-e 3.6` wouldn't work because the correct syntax for this part is `-e py36`. But we also heavily rely on the current `python` by using `-e python` (especially in the CI, using `TOXENV` var: https://github.com/aio-libs/multidict/blob/37c9c87/.github/workflows/python-tests.yml#L24-L26). This just picks up whatever `which python` points to, which is great for CI.

I'm currently not 100% sure how this should look for the dev flow: maybe we just need a number of separate targets, or maybe we could just rely on the current Python too. The biggest challenge is to figure out what is the best UX for us.

**Comment by webknjaz** [comment]
@hmajid2301 it could also be helpful if you could record the use of the make target with https://asciinema.org.
