### ISSUE TITLE
Empty list instead of KeyError for getall missing keys

### ISSUE THREAD

**Issue by Exahilosys** [aio-libs/multidict#382]
**Is your feature request related to a problem? Please describe.**
Raising KeyError in **getall** seems redundant. The answer to "what are the values against this key?" should be "none" instead of "the key doesn't exist", which answers another question.

**Describe the solution you'd like**
mdict.getall('keythatdoesntexist') -> [] instead of raising KeyError

**Comment by asvetlov** [comment]
Please use `mdict.getall('keythatdoesntexist', [])`
API change doesn't worth breaking the backward compatibility
