### ISSUE TITLE
Cannot install 4.6.0 on alpine w/o a compiler

### ISSUE THREAD

**Issue by dave-shawley** [aio-libs/multidict#390]
**Describe the bug**
Just noticed that Cython defaults to "on" now instead of only being enabled when Cython is installed.  Several of our alpine-based docker builds use yarl which uses multidict broke today since there is not a compiler readily available on them.  Defining `MULTIDICT_NO_EXTENSIONS=1` in the environment works around the problem to some degree.  This may be a regression of #280 .

**To Reproduce**   
```
$ docker run --rm -it python:3.8-alpine
/ # pip install -q multidict==4.5.2
/ # pip uninstall -qy multidict
/ # pip install -q multidict==4.6.0
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-qdzrpzdn/multidict/setup.py'"'"'; __file__='"'"'/tmp/pip-install-qdzrpzdn/multidict/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-txo7rqag --python-tag cp38
       cwd: /tmp/pip-install-qdzrpzdn/multidict/
  Complete output (49 lines):
  **********************
  * Accellerated build *
  **********************
...
```

**Expected behavior**
Installing multidict 4.6.0 works on alpine

**Comment by webknjaz** [comment]
This is by design. We want the optimized version to be the default one.
If you don't want speed-ups, you have to explicitly opt-out by using `MULTIDICT_NO_EXTENSIONS` env var.

**Comment by asvetlov** [comment]
I wonder how many environments accidentally use aiohttp stack with implied penalty gap.

**Comment by dave-shawley** [comment]
@asvetlov 

> I wonder how many environments accidentally use aiohttp stack with implied penalty gap.

You can count my work environment as one.  We are certainly using the unoptimized version in a number of production projects.  I am going to fix that shortly though.  I wish that there was a nicer way to raise awareness about this issue but having the installation explode certainly did the trick for me.

The worst part about this specific case was that it was a transitive dependency.  We hard pin the version of `yarl` but not the transitive dependencies ... that one is on me for not pinning the entire frozen/intended environment.  We found out about the change when our CI pipeline failed to build the docker image   -_-

Maybe adding a note in the readme about the environment variable and the performance penalty implied by disabling the speedup.  I found it pretty quickly by looking at _setup.py_.  Is there an analysis that shows the performance gains anywhere?  Being the this is used _everywhere_ during HTTP processing, I can certainly see how the impact to aiohttp would be notable.

**Comment by asvetlov** [comment]
The README update sounds like an excellent idea!

**Comment by asvetlov** [comment]
PyPI doesn't support Alpine wheels yet. There was a discussion about adding a spec for Linux target platform but, well, wheels spin slowly.
That's why I can build Apline wheels but cannot publish them.
You can do it on your own though: use a separate container with compilation toolset installed to build binary wheels, push these files somewhere in a mounted volume, and reuse wheels on building the target image.

**Comment by asvetlov** [comment]
Compiled multidict is about 10-25 times faster than pure Python (depends on the operation set used for benchmarking).
For yarl the gap is even larger.
For aiohttp the difference is not so dramatic usually because the optimization doesn't help so much for io-bound tasks but the gap is the magnitude of times still. It depends on the real application code as usual though.

**Comment by dave-shawley** [comment]
I was following the manylinux discussion on `[Distutils]` a while back.  Since we are building a lot of alpine-based docker containers, using a mounted volume and the setup tools find-packages option might be a pretty nice route.  Thanks for the prod in that general direction.

**Comment by webknjaz** [comment]
@dave-shawley FYI I think it could be useful for you to use https://github.com/jazzband/pip-tools project for pinning transitive deps.
Also, take a look at the multi-stage builds feature in Docker: it basically allows you to use a separate container for building things and then copy the results (wheelhouse?) into the target one as a part of the build process.
