### ISSUE TITLE
Add `rtd-bot` as a maintainer to RTD to make rtd-helper work

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/multidict#402]
I've disabled it.

**Comment by webknjaz** [comment]
Have you actually added the user to the project on RTD?

**Comment by asvetlov** [comment]
I did not add the bot, so I did not set it up.
Used this issue to make the disabling visible to everybody who is subscribed to the project.
That's it.

**Comment by webknjaz** [comment]
I think I ask you to add it there a few times. It's useful to have PR previews...

**Comment by asvetlov** [comment]
You have an option to setup it properly.
Otherwise, I don't care.

**Comment by webknjaz** [comment]
I don't have the access to RTD. That's why I'm asking you to add a user called `rtd-bot` as a maintainer of https://readthedocs.org/projects/multidict/. This way, it'll be able to publish "preview" pages.

**Comment by asvetlov** [comment]
`rtd=bot` is added.
What is *your* RTD account?
I prefer to add you for such maintenance jobs :)

**Comment by webknjaz** [comment]
Same as usual. `webknjaz`

**Comment by asvetlov** [comment]
You are added as the maintainer.
Please feel free to ask me if you need the same for other projects on ReadTheDocs.
