### ISSUE TITLE
istrs preserve the capitalisation, contrary to the documentation

### ISSUE THREAD

**Issue by JustAnotherArchivist** [aio-libs/multidict#419]
**Describe the bug**
Per the [documentation](https://multidict.readthedocs.io/en/stable/multidict.html#istr), `multidict.istr` is a title-cased string, and `istr("STRING")` is `"String"` internally. However since the recent merging of #387, this is no longer the case: the capitalisation is preserved instead.

**To Reproduce**

    > python3 -c 'import multidict; print(repr(multidict.istr("STRING")))'

**Expected behaviour, and actual behaviour up to version 4.5.2**

    "String"

**Actual behaviour since version 4.6.0**

    "STRING"

**Your version of the Python**
3.6.9

**Your version of the multidict distribution**
4.6.0, 4.6.1, and 4.7.0

**Additional context**
In addition to the behaviour contradicting the documentation, this brings back aiohttp bugs https://github.com/aio-libs/aiohttp/issues/813 and https://github.com/aio-libs/aiohttp/issues/934.

**Comment by asvetlov** [comment]
Thanks for the appointment, I should update the doc.
I'm curious how it affects aiohttp; since aiohttp 3.4 (1.5 years old) headers are manually converted to CamelCase: https://github.com/aio-libs/aiohttp/blob/v3.4.0/aiohttp/hdrs.py

It is better because some headers were broken by automatic title-casing, e.g. `Sec-WebSocket-Key`  and `TE` were converted to `Sec-Websocket-Key` and `Te` before this fix.

**Comment by JustAnotherArchivist** [comment]
Ah, I didn't realise that aiohttp fixed this; it is indeed a much better solution! I'm using an older version due to doing very low-level modifications of private APIs to access the raw data stream (with transfer encoding intact etc.) in [qwarc](https://git.kiska.pw/JustAnotherArchivist/qwarc), which wouldn't be portable across aiohttp versions. 2.3.10 was the current version when I started that, and I never ported my hacks to newer releases. (Yes, I'm fully aware that this is very poor practice, and I've been meaning to replace that part of qwarc and/or submit a patch to aiohttp for a while. The code was originally written in a hurry to archive a particular website within a tight deadline and later simply refactored into a reusable package but never properly cleaned up.)
