### ISSUE TITLE
Wheel support for linux aarch64

### ISSUE THREAD

**Issue by odidev** [aio-libs/multidict#500]
**Summary**
Installing multidict on aarch64 via pip using command "pip3 install multidict" tries to build wheel from source code

**Problem description**
multidict don't have wheel for aarch64 on PyPI repository. So, while installing multidict via pip on aarch64, pip builds wheel for same resulting in it takes more time to install multidict. Making wheel available for aarch64 will benefit aarch64 users by minimizing multidict installation time.

**Expected Output**
Pip should be able to download multidict wheel from PyPI repository rather than building it from source code.

@multidict-taem, please let me know if I can help you building wheel/uploading to PyPI repository. I am curious to make multidict wheel available for aarch64. It will be a great opportunity for me to work with you.

**Comment by webknjaz** [comment]
Hello, there's no standard for such wheels so it's not technically possible to put them on PyPI. It only accepts manylinux wheels.

**Comment by odidev** [comment]
@webknjaz Manylinux2014 has given Linux AArch64 support. I have successfully build manylinux2014 wheel for same platform. I can help in this activity.

Also please reopen the issue so that we can work on this and let me know if you have any questions.

Thanks

**Comment by webknjaz** [comment]
TIL

**Comment by webknjaz** [comment]
This will probably require changing https://github.com/aio-libs/multidict/blob/master/.azure-pipelines/deploy.yml

**Comment by webknjaz** [comment]
The only concern I have is that it's probably hard to cross-compile aarch64 in Azure.

**Comment by webknjaz** [comment]
I'm curious if https://www.worksonarm.com/projects/ would help with this.

**Comment by odidev** [comment]
@webknjaz We can use qemu to run an aarch64 build on x86 machine. Please let me know your thoughts here.

**Comment by webknjaz** [comment]
If you can make it work, send a PR and I'll review it.

**Comment by odidev** [comment]
Thanks @webknjaz I will work on it and update you.

**Comment by webknjaz** [comment]
I have one extra note on this. Adding a new platform implies increasing the maintenance burden. Please do not expect the maintainers to invest too much effort into this if it starts failing in the future.

If you want to ensure that it'll keep working, you'll need to commit to contributing some effort should any related problems arise.

**Comment by odidev** [comment]
sure @webknjaz, I will be taking care of the failures in future. Thanks.

**Comment by odidev** [comment]
Hi @webknjaz ,

I have added support for azure pipeline for aarch64 using qemu. I am successfully able to run the test cases.
Please have a look on the changes:
https://github.com/odidev/multidict/commit/61cd26b0668f62ecd8b81bbd827f354ab525a206

Below is the link for azure pipeline logs for aarch64:
https://dev.azure.com/odidev0187/odidev/_build/results?buildId=33&view=results

I tried running deploy pipeline using deploy.yml but I am getting authorization error.
Please review the changes and give your suggestions for the deployment of wheels.

Thanks

**Comment by webknjaz** [comment]
I'd prefer to review a PR instead.

**Comment by webknjaz** [comment]
Most of it should be done against the template repo and then used here.

**Comment by mattsplats** [comment]
@odidev just checking on this, can you open a PR with your changes?

**Comment by webknjaz** [comment]
@mattsplats he did, but in the wrong repo: https://github.com/aio-libs/multidict/pull/519

**Comment by mattsplats** [comment]
@webknjaz As per [comment on the PR](https://github.com/aio-libs/multidict/pull/519#issuecomment-706303388), please take a look at the pipelines repo change: https://github.com/aio-libs/azure-pipelines/pull/1

**Comment by asvetlov** [comment]
Done by multidict 5.0.0 release
