### ISSUE TITLE
multidict 5.0 on PyPI is missing win32 wheels

### ISSUE THREAD

**Issue by SomberNight** [aio-libs/multidict#550]
There are no 32 bit windows wheels uploaded to PyPI for multidict 5.0.0. (only 64 bit)
There are both 32 bit and 64 bit windows wheels uploaded for multidict 4.x.

I cannot see anything about this in the changelog.
Could you please clarify if this is intentional or merely an oversight?

Compare
https://pypi.org/project/multidict/4.7.6/#files
https://pypi.org/project/multidict/5.0.0/#files

**Comment by SomberNight** [comment]
similar issue for yarl: https://github.com/aio-libs/yarl/issues/535

**Comment by asvetlov** [comment]
It is the oversight, sure.
I've migrated the release process from Azure Pipelines to Github Actions and missed this point :(

I'm working on publishing the bug fix version.

**Comment by SomberNight** [comment]
Thank you; much appreciated :)

**Comment by asvetlov** [comment]
You are welcome!
