### ISSUE TITLE
multidict._multidict.so is not distributable

### ISSUE THREAD

**Issue by alex-eri** [aio-libs/multidict#57]
with gdb
```
Program received signal SIGILL, Illegal instruction.
0x00007ffff00b34aa in PyInit__multidict () from /opt/spot4/bin/lib/python3.6/multidict._multidict.so

```

I moved cx_freezed code to fresh installed debian. `ldd` has no missed libs. But there is this trouble.

After deleting it All other libs loaded successfully. And previous version of aiohttp works well after moving.

**Comment by fafhrd91** [comment]
then it is cython bug. are you sure you are not using precompiled .so file?

**Comment by alex-eri** [comment]
Another modules works perfect. And all worked good before aiohttp start using it.

I delete multidict._multidict.so so i sure.

Why multidict raises this error? Maybe setup script makes optimisations not portable...

**Comment by AraHaan** [comment]
When you installed multidict did you tell it from source only or not? This is because if you do not tell it from source only it will try to pip install using the wheels where the extension modules would not get built.

**Comment by asvetlov** [comment]
outdated
