### ISSUE TITLE
Multidict preserves order- document it somewhere

### ISSUE THREAD

**Issue by tmbb** [aio-libs/multidict#62]
As it is implemented now, Multidict preserves order.
Because of the way it is used in aiohttp (parsing post items and HTTP headers), this seems a very desirable property, and not merely an implementation detail.

I think it should be documented both here and in aiohttp's docs that Multidict preserves order, so that one doesn't need to read the implementation to be sure.

**Comment by asvetlov** [comment]
Fixed
