### ISSUE TITLE
CIMultiDict has incompatible type Dict[istr, str]

### ISSUE THREAD

**Issue by rugleb** [aio-libs/multidict#644]
## Long story short

The `mypy` checks fail if the dictionary keys passed to the constructor are of the `istr` type.

## Expected behaviour

The `mypy` checks have passed.

## Actual behaviour

Error from `mypy`:

```text
headers.py:5: error: Argument 1 to "CIMultiDict" has incompatible type "Dict[istr, str]"; expected "Union[Mapping[Union[str, istr], Any], Dict[Union[str, istr], Any], MultiMapping[Any], Iterable[Tuple[Union[str, istr], Any]]]"
```

## Steps to reproduce

Run `mypy` on this script:

```python3
from aiohttp import hdrs
from multidict import CIMultiDict, CIMultiDictProxy

headers = CIMultiDictProxy(
    CIMultiDict({
        hdrs.CONTENT_LENGTH: "40",
        hdrs.CONTENT_TYPE: "text/xml",
    })
)
```

## Your environment

Python v3.9.4
aiohttp v3.7.4.post0
multidict v5.1.0
mypy v0.910

**Comment by asvetlov** [comment]
Would you make a Pull Request with fix?

**Comment by rugleb** [comment]
Yes!

**Comment by rugleb** [comment]
I don't quite understand how to fix it.
I thought that i should fix the [_Arg](https://github.com/aio-libs/multidict/blob/master/multidict/__init__.pyi#L42) type, but it already support `Mapping[_S, _T]` where [_S = Union[str, istr]](https://github.com/aio-libs/multidict/blob/master/multidict/__init__.pyi#L20). So, I'm confused.

**Comment by asvetlov** [comment]
The PR breaks aiohttp and almost every project that depends on multidict.
Should revert it, sorry.

**Comment by sataset** [comment]
@asvetlov will this be implemented in future?

i assume currently the only solution is to override typing annotation on user side
