### ISSUE TITLE
Implement Serializater in order to support JSON.

### ISSUE THREAD

**Issue by Josh-Marshall-FactSet** [aio-libs/multidict#655]
## Long story short

I have a use case where having the ability to serialize to JSON would allow for concise handling of case-insensitive multidicts.  There are a few different approaches listed at https://stackoverflow.com/questions/3768895/how-to-make-a-class-json-serializable

## Expected behaviour

```
>>>import json, multidict
>>> json.dumps(multidict.CIMultiDict([("a", 1), ("a", 2), ("A", 3)]))
'{"a": 1, "a": 2, "A": 3}'
```

## Actual behaviour

```
>>> import multidict, json
>>> json.dumps(multidict.CIMultiDict([("a", 1), ("a", 2), ("A", 3)]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type CIMultiDict is not JSON serializable
```

**Comment by webknjaz** [comment]
> ```
> '{"a": 1, "a": 2, "A": 3}'
> ```

This is not real JSON. It wouldn't allow you to have duplicate keys. Do you even have the tooling able to consume invalid JSON?

**Comment by asvetlov** [comment]
https://datatracker.ietf.org/doc/html/rfc8259#section-4

> The names within an object SHOULD be unique.

It is an invalid JSON according to RFC.

**Comment by Josh-Marshall-FactSet** [comment]
That is an incorrect assessment.  Should, defined here (https://datatracker.ietf.org/doc/html/rfc2119#section-3) does not mean forbid.  It is allowed, but is bad practice.

**Comment by asvetlov** [comment]
Ok. Why multidict should care about bad practices?
You can generate such representation by hand if you really need it.
