### ISSUE TITLE
Should there not be type definitions for get as well?

### ISSUE THREAD

**Issue by sebbASF** [aio-libs/multidict#686]
https://github.com/aio-libs/multidict/blob/572ce02e72208e33a986c398559f309e83fe2b0d/multidict/__init__.pyi#L40

When testing 6.0.1 with mypy, I get an error for d.get("key"), but not d.getone("key", None).
Likewise for d.get("key", "val") and d.getone("key", "val")

I would expect these both to pass mypy - or at least to both fail or pass.

**Comment by asvetlov** [comment]
Fixed by #688
