### ISSUE TITLE
Wheels for CPython 3.11

### ISSUE THREAD

**Issue by altendky** [aio-libs/multidict#778]
## Long story short

Publishing CPython 3.11 wheels to PyPI would help other projects that use multidict and are working on their own CPython 3.11 support and distribution.

## Expected behaviour

pip is able to install multidict wheels from PyPI with CPython 3.11.

## Actual behaviour

The sdist is downloaded instead such that building is required.

## Steps to reproduce

Look on PyPI and note there are no `cp311` wheels available.

## Your environment

We operate on all platforms, Intel and ARM, and CPython 3.7 through 3.11.

**Comment by webknjaz** [comment]
Done: https://github.com/aio-libs/multidict/actions/runs/3606572155/jobs/6078467624#step:7:1570
