### ISSUE TITLE
Update from multidict==1.2.2 to latest cause Flask app behind a nginx proxy to 404

### ISSUE THREAD

**Issue by bart3005** [aio-libs/multidict#8]
I am have a Flask app hosted in a gunicorn server behind a nginx reverse proxy. The app is not on the / URL but under a 

Updating from 1.2.2 to latest cause the Flask app to return 404 for all routes. Downgrading back to 1.2.2 fixed the issues.

Not sure if this is a Flask issue or multidict.

**Comment by asvetlov** [comment]
aiohttp actually.
The master uses 2.0 but the latest published release still sits on 1.2.2

**Comment by bart3005** [comment]
Thanks heaps explains it.
