### ISSUE TITLE
Equality operator 

### ISSUE THREAD

**Issue by bloowitt** [aio-libs/multidict#823]
## Long story short

MultiDict comparison seems not to be stable to key ordering, unline standard Python dictionary. Can't find a reference in documentation as to this being expected/standard behaviour for the library - please do close if this is expected behaviour.

```
>>> import multidict
>>> a = multidict.CIMultiDict({"a": "A", "b": "B"})
>>> b = multidict.CIMultiDict({"b": "B", "a": "A"})
>>> a == b
False
```

whereas

```
>>> b = {"b": "B", "a": "A"}
>>> a = {"a": "A", "b": "B"}
>>> a == b
True
```

I think this comes from __eq__ comparing .items() on left and right without sorting in any way (https://github.com/aio-libs/multidict/blob/15672bb6c6622856ff33a986f34e1307b610978a/multidict/_multidict_py.py#L115-L123)

## Expected behaviour

In the above example, I'd expect a and b to be equal.

## Actual behaviour

Equality evaluation is False

## Steps to reproduce

Code sample is self contained.

```
>>> import multidict
>>> a = multidict.CIMultiDict({"a": "A", "b": "B"})
>>> b = multidict.CIMultiDict({"b": "B", "a": "A"})
>>> a == b
```

## Your environment

Testing on `poetry run python` interactive console on a project using multidict for server stuff (behaviour observed during testing of the project, but console is minimal setup).

**Comment by rahulnegi20** [comment]
```
     for (i1, k2, v1), (i2, k2, v2) in zip(lft, rht): 
         if i1 != i2 or v1 != v2: 
```

what is k2 here?

**Comment by rahulnegi20** [comment]
Hi @DavidRomanovizc, 

I submitted a [PR ](https://github.com/aio-libs/multidict/pull/843)for this issue, 
but getting some checks failed. 
But it is working fine in my machine 😶‍🌫️, all test cases are getting passed. 

Where I can find any brief about submitting a PR or related docs.

Thanks

**Comment by DavidRomanovizc** [comment]
If you still need to compare using the == operator, you can use the following construct, which returns True:

```python
d1 = CIMultiDict({"a": "A", "b": "B"})
d2 = CIMultiDict({"b": "B", "a": "A"})

assert sorted(d1.items()) == sorted(d2.items())
```

**Comment by rahulnegi20** [comment]
![title](https://tenor.com/bvFhz.gif)

**Comment by danielknell** [comment]
`sorted()` will only work when the items are consistently cased...

```pycon
>>> a = multidict.CIMultiDict({'A': 'b'}) 
>>> b = multidict.CIMultiDict({'a': 'b'})
>>> a == b
True
>>> sorted(a.items()) == sorted(b.items())
False
```

this makes writing tests for things using `aiohttp` harder as any refactoring which changes the order keys are added will fail... even though that is semantically not a change.

should `aiohttp` not be using this library for things like headers? if so i will go raise an issue there and reference your response here.

**Comment by eventlistener** [comment]
@DavidRomanovizc I too find it confusing that a dict-like object behaves differently from the standard dict in terms of equality testing. I'd also like to note that the `__eq__` operator is not transitive in the current implementation:

```python
>>> d1 = dict([('foo', 'bar'), ('baz', 'quux')])
>>> d2 = dict([('baz', 'quux'), ('foo', 'bar')])
>>> md1 = multidict.MultiDict([('foo', 'bar'), ('baz', 'quux')])
>>> md2 = multidict.MultiDict([('baz', 'quux'), ('foo', 'bar')])

>>> assert d1 == d2
>>> assert md1 == d1
>>> assert md1 == d2
>>> assert md2 == d1
>>> assert md2 == d2
>>> assert md1 == md2
```

In the provided example, all assertions pass _except the last one_, which means that the chain `md1 == d1 == d2 == md2` is not valid, despite each individual equality test within the chain passing successfully.


If this is expected behavior and the maintainers have no plans to change it, would you at least be open to the addition of another `*MultiDict` class and its corresponding proxy that is more consistent with the standard dict in terms of equality testing? I might be interested in contributing.
