### ISSUE TITLE
Cibuild wheel setup is broken

### ISSUE THREAD

**Issue by hoodmane** [aio-libs/multidict#837]
## Long story short

@henryiii and I were investigating your cibuildwheel setup and there appear to be two problems with it:
1. The wheel that is tested is different than the wheel that is placed in the wheelhouse #827.
2. In CI, the import here: https://github.com/aio-libs/multidict/blob/master/multidict/_compat.py#L12 fails due to a circular import and so USE_EXTENSIONS is set to false, so tests are skipped due to "No extensions available".

When you have time, @henryiii or I would be happy to submit a patch to fix the USE_EXTENSIONS problem.

**Comment by webknjaz** [comment]
Thank you! I'll try to fix the second problem while remaking the packaging setup.

**Comment by webknjaz** [comment]
The second point is going to be addressed by #915

**Comment by hoodmane** [comment]
Thanks @webknjaz!
