### ISSUE TITLE
segmentation fault on getall

### ISSUE THREAD

**Issue by andynrw** [aio-libs/multidict#898]
## Actual behaviour

multidict.CIMultiDict().getall("test") => KeyError: 'test'
multidict.CIMultiDict().getall("test", default=None) => Fatal Python error: Segmentation fault

## Your environment
Fedora 39
Python 3.12.0
multidict 6.0.4

**Comment by JoeriHermans** [comment]
Same behaviour on OSX and Python 3.12.1.

**Comment by zmedico** [comment]
Looks the same as https://github.com/aio-libs/multidict/issues/868 which https://github.com/aio-libs/multidict/pull/889 fixes.

**Comment by webknjaz** [comment]
It seems this was fixed by 780a1e1.
