### ISSUE TITLE
`MultiDict.copy` returns a `MultiDict` instance when a subclass' `.copy` method is used

### ISSUE THREAD

**Issue by provinzkraut** [aio-libs/multidict#901]
## Long story short

When calling `.copy` on a subclass of `MultiDict`, an instance of `MultiDict` is returned instead of an instance of the subclass.

## Expected behaviour

`MultiDict.copy` to return an instance of the subclass

## Actual behaviour

An instance of `MultiDict` is returned

## Steps to reproduce

```python
from multidict import MultiDict

class MyMultiDict(MultiDict):
  pass

assert isinstance(MyMultiDict().copy(), MyMultiDict)
```

## Your environment

- `multidict` version 6.0.4

**Comment by webknjaz** [comment]
Is this even possible? Do you have any example implementing such a feature? The base class doesn't know what kind of changes there are in the child class — how would it know that it's safe to construct it? You might have to override this method in the child class.

**Comment by webknjaz** [comment]
This is how inheritance works, typically:
```pycon
>>> class MyDict(dict): ...
... 
>>> my_dict = MyDict()
>>> my_dict_copy = my_dict.copy()
>>> type(my_dict)
<class '__main__.MyDict'>
>>> type(my_dict_copy)
<class 'dict'>
```
If you want a custom class, make override the method.

**Comment by provinzkraut** [comment]
> Is this even possible? Do you have any example implementing such a feature?

Sure is!

```python
class Foo:
  def copy(self):
    return type(self)()

class Bar(Foo):
  pass

assert isinstance(Bar().copy(), Bar)
```

> The base class doesn't know what kind of changes there are in the child class — how would it know that it's safe to construct it?

That's true, but I'd say it does make sense to assume that the child class behaves properly (e.g. doesn't violate the Liskov substitution principle) and it's safe to create a new instance of it in the same way you can instantiate the base class.

> This is how inheritance works, typically:

Counterpoint: 

```python
class MyDict(dict):
 pass

assert isinstance(MyDict.fromkeys([]), MyDict)
``` 

`collections.UserDict` also implements this functionality, which is how Python wants you to create your custom dicts:

```python
from collections import UserDict

class MyDict(UserDict):
 pass

assert isinstance(MyDict.fromkeys([]), MyDict)
```

I wouldn't say that this is *typically* how inheritance works. Personally, I feel the more [pythonic](https://docs.python.org/3/glossary.html#term-EAFP) way is to use subclasses by default and if a user breaks this, it's their responsibility to properly adapt their subclass.

**Comment by webknjaz** [comment]
Well, if you send a PR, I'll be happy to review it. But it should be fully covered with tests and have the same behavior in in both Python and C implementations. But I'm not planning to be working on the implementation myself.
