### ISSUE TITLE
[TODO] Hit 100% coverage in `multidict/_multidict_base.py`

### ISSUE THREAD

**Issue by webknjaz** [aio-libs/multidict#921]
Currently, the coverage of this module is partial. Staring at https://app.codecov.io/github/aio-libs/multidict/commit/61f241fbfc4b507e8c44d7d8e60d3fc4414cc91f/blob/multidict/_multidict_base.py will help the contributor identify fully or partially uncovered lines.

The related tests are in https://github.com/aio-libs/multidict/blob/master/tests/test_multidict.py. The contributions can be made in small chunks. Submitting even a single test that improves coverage is great! It's also easier to accept/review smaller PRs.

In most cases, making new tests can be done by example. Starting with copying an existing test and tweaking it to hit different code branches...

**Comment by Jamim** [comment]
_Hi @webknjaz,_

It's nice that this project have the highest coverage target possible, but the fact that Codecav enforces this target makes **any** PR marked with ❌ now, even though a PR could increase coverage, such as #927. I suggest disabling that check or lowering the target until 100% coverage is actually achieved.

_Thanks!_

**Comment by webknjaz** [comment]
That check is not enforced. Besides, due to Codecov's flakiness, it's not always accurate.

**Comment by a5r0n** [comment]
The last uncovered line is the `GenericAlias` for python versions older than 3.9
